[package]
name = "boson"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.2", features = ["derive", "unicode"] }
rayon = "1.9.0"
tokio = { version = "1.36.0", features = [
    "fs",
    "macros",
    "sync",
    "rt-multi-thread",
] }
